# Assignment 01

Buatlah fungsi untuk melakukan preprocessing dan ekstraksi ciri TF-ID pada data teks tanpa menggunakan library.

Atha Putra Fausta

24/538657/PA/22864

## Dataset Description

Source: https://www.kaggle.com/datasets/christph/harry-potter-potion-recipes

The dataset contains all potion recipes in the Harry Potter universe, collected from various fan pages and wikis, which contains the following columns:

Recipe: the steps required to brew the potion, e.g. "Add Wormwood. Stir 5 times"

Name: name of the potion, e.g. "Shrinking Potion"

Description: effect of the potion, e.g. "temporarily turns the drinker's head into a pumpkin"

ATC: classification of the potion category using the ATC coding system.

For this TF-IDF feature extraction, the description column is used for the corpus.

## Importing the data

In [1]:
import pandas as pd
df = pd.read_csv("data/hp_potions.csv")
df

,Recipe,Name,Description,ATC
0,Add crushed snake fangs to your cauldron and s...,Cure for Boils,potion which removed boils,Dermatologicals
1,Add 2 drops of Lethe River Water to your cauld...,Forgetfulness Potion,potion which caused an unknown degree of memor...,Nervous system
2,Add 4 lionfish spines to the mortar. Crush int...,Herbicide Potion,poisonous potion that killed or damages plants,"Antiparasitic products, insecticides and repel..."
3,Add 4 sprigs of Lavender to the mortar. Add 2 ...,Sleeping Draught,sleeping potion,Nervous system
4,Add salamander blood until the potion turns re...,Wiggenweld Potion,The Wiggenweld Potion was a healing potion wit...,Nervous system
...,...,...,...,...
69,Add Bitter root. Add Snowdrop. Add Abraxan hai...,Strong Exstimulo Potion,Strongly boosts spell-casting power of the dri...,various
70,Add Honeywater. Add Vervain infusion. Add scur...,Strong Invigoration Draught,Significantly boosts the energy and focus of t...,Nervous system
71,Add Jobberknoll feathers.,Truth Serum,Force the drinker to tell the truth,Nervous system
72,Add Honeywater. Add Mint sprigs. Add Stewed Ma...,Volubilis Potion,Alters the drinker's voice,Semsory organs
73,Add Wolfsbane.,Wolfsbane Potion,Allows werewolves to keep their minds post-tra...,Nervous system

In [2]:
# Only the description column is selected for the corpus
documents = df["Description"].tolist()
documents

['potion which removed boils',
 'potion which caused an unknown degree of memory loss in the drinker.',
 'poisonous potion that killed or damages plants',
 'sleeping potion',
 'The Wiggenweld Potion was a healing potion with the power to cure injuries, and was the antidote to the Sleeping Draught and the Draught of Living Death.',
 'antidote',
 "temporarily turned the drinker's head into a pumpkin.",
 'potion used to move through flames unscathed, also known as ice potion',
 'potion which caused whatever it touched to swell in size.',
 "potion that caused the drinker's hair to stand on end",
 'potion that gave the consumer prolonged endurance',
 'confusion',
 'potion that caused the drinker to shrink to a smaller form',
 'potion which prevented the drinker from falling asleep and could also be used to awaken someone from drugging or concussion. It acted as an antidote for the Draught of Living Death.',
 'foul smelling potion used to spray Doxies. It paralysed them for a period of time, allowing the user to safely remove the Doxies without fear of being bitten',
 'potion which allowed the drinker to think more clearly',
 'potion that was used to calm a person down after they have had suffered a shock, trauma, or emotional outburst.',
 'potion which cured the common cold and warmed up the recipient',
 'potion which caused the drinker to temporarily become older',
 'potion and a highly potent poison',
 'potion which restored bones.',
 'home remedy',
 'potion which relieved anxiety and agitation.',
 "potion which presumably boosted the drinker's energy.",
 "potion that gave the drinker 'a burst of energy', greatly sharpening one's reflexes",
 'potion that granted the drinker immense strength.',
 'potion which caused the drinker to become belligerent and reckless',
 'It was highly explosive when it was touched by an outside source.',
 'potion that induced a sense of inexplicable, irrational happiness upon the drinker',
 'potion that made the drinker lucky for a period of time, during which everything they attempt would be successful.',
 'love potion',
 'Sleeping Draught',
 'potion that allowed the drinker to assume the form of someone else.',
 'antidote',
 'potion that induced laughter in the drinker',
 "potion which improved the drinker's memory, boosting their mental cognition",
 'potion which caused irrational decision making in the drinker',
 'fumes induced hysterical laughter.',
 'poison',
 'potion that caused the drinker to babble nonsense',
 'poison',
 "potion that supposedly increased the drinker's brain power",
 'A potion that makes the taker very beautiful.',
 'love potion',
 'treats acne',
 'poison',
 'soothing balsam',
 'potion was widely used and proved to be extremely useful to members of the Statute of Secrecy Task Force during the Calamity, who used it to handle particularly unstable Foundable traces',
 'poison',
 'poison',
 'healing potion, used to cure sick dragons',
 'potion used to help magical plants grow',
 'volatile potion',
 'Increases the spell power of a single spell cast',
 'scam',
 'Treats ringworm, fungicide',
 'treats common cold',
 'Temporary invisibility',
 'laxative',
 'Serves as an antidote for Love Potion',
 'poison',
 'Soothes and heals cuts and abrasions',
 "potion that restored the drinker's eyesight",
 'poison',
 'poison',
 'Helps restore non-corporeal wizards to their bodies',
 'Helps restore non-corporeal wizards to a rudimentary bodies/sustains rudimentary bodies',
 'hair care potion',
 'medicinal balm for soothing sores and wounds',
 'Strongly boosts spell-casting power of the drinker for four spell casts',
 'Significantly boosts the energy and focus of the drinker',
 'Force the drinker to tell the truth',
 "Alters the drinker's voice",
 'Allows werewolves to keep their minds post-transformation']

## Text Preprocessing

In this step, the documents are converted to lowercase, and punctuation and stop words are removed.

In [3]:
stop_words = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't", 'potion', 'drinker', 'drinkers', 'caused', 'used', 'treats', 'induced']

stop_words

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'potion',
 'drinker',
 'drinkers',
 'caused',
 'used',
 'treats',
 'induced']

In [4]:
punctuations = ".,!?;:'\"()-[]{}_/@#$%^&*+=<>`~|\\"

punctuations

'.,!?;:\'"()-[]{}_/@#$%^&*+=<>`~|\\'

In [5]:
# Cleaning Function
def cleaning(text, stop_words, punctuations):
    text = text.lower().replace('\n', ' ')
    text = ''.join(c for c in text if c not in punctuations)
    return ' '.join(w for w in text.split() if w not in stop_words)


docs_cleaned = [cleaning(doc, stop_words, punctuations)
                for doc in documents]

docs_cleaned

['removed boils',
 'unknown degree memory loss',
 'poisonous killed damages plants',
 'sleeping',
 'wiggenweld healing power cure injuries antidote sleeping draught draught living death',
 'antidote',
 'temporarily turned head pumpkin',
 'move flames unscathed also known ice',
 'whatever touched swell size',
 'hair stand end',
 'gave consumer prolonged endurance',
 'confusion',
 'shrink smaller form',
 'prevented falling asleep could also awaken someone drugging concussion acted antidote draught living death',
 'foul smelling spray doxies paralysed period time allowing user safely remove doxies without fear bitten',
 'allowed think clearly',
 'calm person suffered shock trauma emotional outburst',
 'cured common cold warmed recipient',
 'temporarily become older',
 'highly potent poison',
 'restored bones',
 'home remedy',
 'relieved anxiety agitation',
 'presumably boosted energy',
 'gave burst energy greatly sharpening ones reflexes',
 'granted immense strength',
 'become belligerent reckless',
 'highly explosive touched outside source',
 'sense inexplicable irrational happiness upon',
 'made lucky period time everything attempt would successful',
 'love',
 'sleeping draught',
 'allowed assume form someone else',
 'antidote',
 'laughter',
 'improved memory boosting mental cognition',
 'irrational decision making',
 'fumes hysterical laughter',
 'poison',
 'babble nonsense',
 'poison',
 'supposedly increased brain power',
 'makes taker beautiful',
 'love',
 'acne',
 'poison',
 'soothing balsam',
 'widely proved extremely useful members statute secrecy task force calamity handle particularly unstable foundable traces',
 'poison',
 'poison',
 'healing cure sick dragons',
 'help magical plants grow',
 'volatile',
 'increases spell power single spell cast',
 'scam',
 'ringworm fungicide',
 'common cold',
 'temporary invisibility',
 'laxative',
 'serves antidote love',
 'poison',
 'soothes heals cuts abrasions',
 'restored eyesight',
 'poison',
 'poison',
 'helps restore noncorporeal wizards bodies',
 'helps restore noncorporeal wizards rudimentary bodiessustains rudimentary bodies',
 'hair care',
 'medicinal balm soothing sores wounds',
 'strongly boosts spellcasting power four spell casts',
 'significantly boosts energy focus',
 'force tell truth',
 'alters voice',
 'allows werewolves keep minds posttransformation']

## Feature Extraction

### Calculating Term Frequency (TF)

In the first step of TF-IDF, the term frequency is calculated.

Term frequency, $tf(t,d)$, is the relative frequency of term $t$ within document $d$

$\text{Term Frequency = }\large{\frac{f_{t,d}}{\sum_{t' \in d}f_{t',d}}}$ , where the numerator represents the count of a given term and the denominator is the total number of terms in document $d$.

In [6]:
def term_freq(document_list):

    '''
    Function that returns the term frequency of given documents

    Parameters
    ----------
    document_list: list or array containing text in string format

    Returns
    -------
    {document: vector} : dictionary containing the original string input as the key
    and the term frequency for the given article
    '''

    combined_string = ' '.join(document_list)
    word_set = [word for word in set(combined_string.split()) if len(word) > 1]

    filtered_docs = []
    for document in document_list:
        filtered_docs.append(' '.join([word for word in document.split() if len(word) > 1]))

    doc_word_count = []
    for document in filtered_docs:
        doc_word_count.append([document.split().count(word)/len(document.split()) for word in word_set])

    return {doc:vector for doc,vector in zip(filtered_docs,doc_word_count)}

In [7]:
def word_list(document_list):

    '''
    Function that returns the unique words for a given list of strings.

    Parameters
    ----------
    document_list: list or array containing text in string format

    Returns
    -------
    [words] : list containing a unique set of words
    '''

    combined_string = ' '.join(document_list)
    return [word for word in set(combined_string.split()) if len(word) > 1]

In [8]:
tf_df = pd.DataFrame(data = term_freq(docs_cleaned).values(),
                  columns = word_list(docs_cleaned),
                  index = term_freq(docs_cleaned).keys())

tf_df

,drugging,recipient,upon,proved,draught,gave,period,restore,useful,inexplicable,...,form,laughter,cured,care,confusion,user,pumpkin,whatever,makes,statute
removed boils,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unknown degree memory loss,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
poisonous killed damages plants,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
sleeping,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wiggenweld healing power cure injuries antidote sleeping draught draught living death,0.0,0.0,0.0,0.0,0.181818,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
strongly boosts spellcasting power four spell casts,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
significantly boosts energy focus,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
force tell truth,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
alters voice,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
allows werewolves keep minds posttransformation,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Calculating Inverse Document Frequency (IDF)

After the term frequency has been calculated, the next step is to calculate the IDF.

The inverse document frequency (idf) is a measure of importance of a term $t$ in a given document $d$. The measure gives a larger weight to terms which are less common in the corpus while more frequent terms across a document are given less weight.

The IDF formula used here implements method similar to Sci-kit Learn module, where it adds a `1` in the numerator and the denominator which is akin to adding a document to the corpus containing every term to prevent a division by zero.

$\text{Inverse Document Frequency = } log \large{\frac{| \ D \ | + 1}{{| \ d : t_i \in \ d  \ | + 1}}} + 1$

In [9]:
import math

def inverse_doc_freq(document_list,unique_words):

    '''
    Function that returns the inverse document frequency for a given set of articles.

    Parameters
    ----------
    document_list: list or array containing text in string format

    Returns
    -------
    idf_list : list containing a unique set of words
    '''

    idf_dict = {}

    for word in unique_words:
        temp_word_list = []
        for sentence in document_list:
            temp_word_list.append(word in sentence)
        idf_dict[word] = temp_word_list.count(True)+1

    idf_list = []

    for value in idf_dict.values():
        idf_list.append(math.log((len(tf_df)+1)/value)+1)

    return idf_list

In [10]:
idf_array = inverse_doc_freq(tf_df.index,tf_df.columns)
idf_array

[4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 3.803360380906535,
 4.091042453358316,
 4.091042453358316,
 3.580216829592325,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 3.580216829592325,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 3.803360380906535,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 3.803360380906535,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 3.803360380906535,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 3.803360380906535,
 3.803360380906535,
 4.091042453358316,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.091042453358316,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 3.803360380906535,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 3.580216829592325,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.091042453358316,
 4.49650756146648,
 3.803360380906535,
 4.091042453358316,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648,
 4.49650756146648]

### Calculating TF-IDF

After TF and IDF has been obtained, the TF-IDF value can now be calculated.

The term frequency-inverse document frequency (tf-idf), is an array of values that represents how important a word is in a given document within a corpus. The higher the tf-idf value is for a word in a document, the more important the word is.

$\text{tf-idf Product = (Term Frequency)(Inverse Document Frequency)}$

$\text{tf-idf =} \Large{\frac{\text{tf-idf Product}}{||\text{tf-idf Product}||}}$

In [11]:
import numpy as np

def tf_idf(term_freq_data,inverse_doc_freq_data):

    '''
    Function that returns the Term Frequency-Inverse Document Frequency (tf-idf).

    Parameters
    ----------
    term_freq_data: dictionary containing the original string input as the key
    and the term frequency for the given article
    inverse_doc_freq_data:

    Returns
    -------
    tf_idf_vector : returns the tf-idf vector given the term frequency and inverse document frequency
    '''

    tf_idf_vector = []
    multiplied_vector = np.array(term_freq_data) * np.array(inverse_doc_freq_data)

    for array in multiplied_vector:
        tf_idf_vector.append(array/(sum(array**2))**.5)

    return tf_idf_vector

In [12]:
tfidf_df = pd.DataFrame(data = tf_idf(tf_df.to_numpy(), np.array(idf_array)),
             columns = word_list(docs_cleaned),
             index = term_freq(docs_cleaned).keys())

tfidf_df

,drugging,recipient,upon,proved,draught,gave,period,restore,useful,inexplicable,...,form,laughter,cured,care,confusion,user,pumpkin,whatever,makes,statute
removed boils,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unknown degree memory loss,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
poisonous killed damages plants,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
sleeping,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wiggenweld healing power cure injuries antidote sleeping draught draught living death,0.0,0.0,0.0,0.0,0.533787,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
strongly boosts spellcasting power four spell casts,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
significantly boosts energy focus,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
force tell truth,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
alters voice,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
allows werewolves keep minds posttransformation,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Result

After preprocessing and feature extracting the text data using TF-IDF. The following results are obtained:

1. From the Harry Potter Potion Recipe dataset, 65 documents are obtained from the description of the recipe.
2. 210 unique words are obtained from the corpus after preprocessing and tokenization.
3. Out of all words, the 5 most important words, according to TF-IDF score, are 'antidote', 'sleeping', 'love', 'laughter', and 'poison'.
4. The extracted feature can then be used for other tasks, such as classification and clustering.

In [13]:
ranked = tfidf_df.mean(axis=0).sort_values(ascending=False)

ranked

antidote    0.030500
sleeping    0.030369
love        0.024306
laughter    0.023708
poison      0.023545
              ...
foul        0.003789
spray       0.003789
fear        0.003789
proved      0.003656
remove      0.003448
Length: 210, dtype: float64

## References

https://yunusmuhammad007.medium.com/tf-idf-term-frequency-inverse-document-frequency-representasi-vector-data-text-2a4eff56cda

https://github.com/ad17171717

https://github.com/Simon-Fukada

https://www.youtube.com/watch?v=iHeOrDH3v1k

https://www.youtube.com/watch?v=f0pZviF6qLQ

https://www.youtube.com/watch?v=cOpi2Im1hFo&t=1811s

https://www.youtube.com/watch?v=BYWBlY-8Pv0